### ISSUE TITLE
Any reason for adding Microsoft.Maui.Controls dependency?

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [Alex-Dobrynin/Controls.UserDialogs.Maui#14]
**Describe the bug**
Adding `Microsoft.Maui.Controls` and its friend causes conflicts with Android package in net8 for Android projects. 
See:
https://github.com/Alex-Dobrynin/Controls.UserDialogs.Maui/blob/master/Controls.UserDialogs.Maui/Controls.UserDialogs.Maui.csproj#L34-L37

Also, these changes were made in a commit named "Increase version," which raises doubts.

**Did you found a workaround?**
Using older version

**Comment by Alex-Dobrynin** [comment]
these were added to support older version of maui if someone don't want to update version of maui in their projects. if don't do this the version of maui will be 8.0.6 required for this library, because i have 8.0.6 MAUI workload installed on my machine (under the hood it will use installed version if not specify explicitly). 
About naming of commits: this is not information for you, this is information for me.
Hope I've answered on your question.

Also, if you want to prove smth, please provide the repro project with conflicts. if not, I will close this issue

**Comment by DmitriyKirakosyan** [comment]
@Alex-Dobrynin thanks for the reply.

It is easy to reproduce, steps: create a net8 mobile app, create android project within it, add userdialogs.maui and use Android.Views.View. You will get this:

> 'View' is an ambiguous reference between 'Microsoft.Maui.Controls.View' and 'Android.Views.View'

Although it can be fixed by specifying the full component path, it is still a compilation error, and thus a breaking change in the library you are distributing.
Regarding your case about supporting older versions. I believe there shouldn't be any issues as the final application will decide whether to add this dependency and which version to use.

Version `1.5.2` works for me, so I'm using it as a workaround.

**Comment by Alex-Dobrynin** [comment]
Have you tried Sample project from this repo? is there the same?



> It is easy to reproduce, steps: create a net8 mobile app, create android project within it, add userdialogs.maui and use Android.Views.View.

please provide the test project (.zip). I don't have time playing with this.

You can try Sample project from this repo and tell me if there is the same behavior as you describe. if not, you should look into your project and find where you did wrong
